//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bank.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Add... ähnelt.
        /// </summary>
        public static string BUTTON_ADD {
            get {
                return ResourceManager.GetString("BUTTON_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Cancel ähnelt.
        /// </summary>
        public static string BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Edit... ähnelt.
        /// </summary>
        public static string BUTTON_EDIT {
            get {
                return ResourceManager.GetString("BUTTON_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _OK ähnelt.
        /// </summary>
        public static string BUTTON_OK {
            get {
                return ResourceManager.GetString("BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Remove ähnelt.
        /// </summary>
        public static string BUTTON_REMOVE {
            get {
                return ResourceManager.GetString("BUTTON_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _About... ähnelt.
        /// </summary>
        public static string CMD_ABOUT {
            get {
                return ResourceManager.GetString("CMD_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Add booking... ähnelt.
        /// </summary>
        public static string CMD_ADD {
            get {
                return ResourceManager.GetString("CMD_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Close ähnelt.
        /// </summary>
        public static string CMD_CLOSE {
            get {
                return ResourceManager.GetString("CMD_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C_onfigure regular bookings... ähnelt.
        /// </summary>
        public static string CMD_CONFIGURE_DEFAULT_BOOKING {
            get {
                return ResourceManager.GetString("CMD_CONFIGURE_DEFAULT_BOOKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Configure default texts... ähnelt.
        /// </summary>
        public static string CMD_CONFIGURE_DEFAULT_TEXT {
            get {
                return ResourceManager.GetString("CMD_CONFIGURE_DEFAULT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create _new account... ähnelt.
        /// </summary>
        public static string CMD_CREATE_ACCOUNT {
            get {
                return ResourceManager.GetString("CMD_CREATE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Delete booking... ähnelt.
        /// </summary>
        public static string CMD_DELETE {
            get {
                return ResourceManager.GetString("CMD_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die D_elete account... ähnelt.
        /// </summary>
        public static string CMD_DELETE_ACCOUNT {
            get {
                return ResourceManager.GetString("CMD_DELETE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete _sheet... ähnelt.
        /// </summary>
        public static string CMD_DELETE_SHEET {
            get {
                return ResourceManager.GetString("CMD_DELETE_SHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Edit booking... ähnelt.
        /// </summary>
        public static string CMD_EDIT {
            get {
                return ResourceManager.GetString("CMD_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E_xit ähnelt.
        /// </summary>
        public static string CMD_EXIT {
            get {
                return ResourceManager.GetString("CMD_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _First ähnelt.
        /// </summary>
        public static string CMD_FIRST {
            get {
                return ResourceManager.GetString("CMD_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Import account... ähnelt.
        /// </summary>
        public static string CMD_IMPORT_ACCOUNT {
            get {
                return ResourceManager.GetString("CMD_IMPORT_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Last ähnelt.
        /// </summary>
        public static string CMD_LAST {
            get {
                return ResourceManager.GetString("CMD_LAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Next ähnelt.
        /// </summary>
        public static string CMD_NEXT {
            get {
                return ResourceManager.GetString("CMD_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Previous ähnelt.
        /// </summary>
        public static string CMD_PREVIOUS {
            get {
                return ResourceManager.GetString("CMD_PREVIOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Rename account... ähnelt.
        /// </summary>
        public static string CMD_RENAME_ACCOUNT {
            get {
                return ResourceManager.GetString("CMD_RENAME_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set _password... ähnelt.
        /// </summary>
        public static string CMD_SET_PASSWORD {
            get {
                return ResourceManager.GetString("CMD_SET_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Update balance... ähnelt.
        /// </summary>
        public static string CMD_UPDATE_BALANCE {
            get {
                return ResourceManager.GetString("CMD_UPDATE_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amount ähnelt.
        /// </summary>
        public static string COLUMN_AMOUNT {
            get {
                return ResourceManager.GetString("COLUMN_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Balance ähnelt.
        /// </summary>
        public static string COLUMN_BALANCE {
            get {
                return ResourceManager.GetString("COLUMN_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        public static string COLUMN_DATE {
            get {
                return ResourceManager.GetString("COLUMN_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Day ähnelt.
        /// </summary>
        public static string COLUMN_DAY {
            get {
                return ResourceManager.GetString("COLUMN_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text ähnelt.
        /// </summary>
        public static string COLUMN_TEXT {
            get {
                return ResourceManager.GetString("COLUMN_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occurred. {0} ähnelt.
        /// </summary>
        public static string ERROR_OCCURRED_0 {
            get {
                return ResourceManager.GetString("ERROR_OCCURRED_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The password does not match. ähnelt.
        /// </summary>
        public static string ERROR_PASSWORD_DOES_NOT_MATCH {
            get {
                return ResourceManager.GetString("ERROR_PASSWORD_DOES_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The password must contain at least 4 characters. ähnelt.
        /// </summary>
        public static string ERROR_PASSWORD_MIN_CHARS {
            get {
                return ResourceManager.GetString("ERROR_PASSWORD_MIN_CHARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The password is wrong. ähnelt.
        /// </summary>
        public static string ERROR_WRONG_PASSWORD {
            get {
                return ResourceManager.GetString("ERROR_WRONG_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Account: ähnelt.
        /// </summary>
        public static string LABEL_ACCOUNT {
            get {
                return ResourceManager.GetString("LABEL_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Amount: ähnelt.
        /// </summary>
        public static string LABEL_AMOUNT {
            get {
                return ResourceManager.GetString("LABEL_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Balance: ähnelt.
        /// </summary>
        public static string LABEL_BALANCE {
            get {
                return ResourceManager.GetString("LABEL_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C_onfirm new password: ähnelt.
        /// </summary>
        public static string LABEL_CONFIRM_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_CONFIRM_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Day: ähnelt.
        /// </summary>
        public static string LABEL_DAY {
            get {
                return ResourceManager.GetString("LABEL_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Default text: ähnelt.
        /// </summary>
        public static string LABEL_DEFAULT_TEXT {
            get {
                return ResourceManager.GetString("LABEL_DEFAULT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Month: ähnelt.
        /// </summary>
        public static string LABEL_MONTH {
            get {
                return ResourceManager.GetString("LABEL_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Name: ähnelt.
        /// </summary>
        public static string LABEL_NAME {
            get {
                return ResourceManager.GetString("LABEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _New password: ähnelt.
        /// </summary>
        public static string LABEL_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C_urrent password: ähnelt.
        /// </summary>
        public static string LABEL_OLD_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_OLD_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Password: ähnelt.
        /// </summary>
        public static string LABEL_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Text: ähnelt.
        /// </summary>
        public static string LABEL_TEXT {
            get {
                return ResourceManager.GetString("LABEL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Year: ähnelt.
        /// </summary>
        public static string LABEL_YEAR {
            get {
                return ResourceManager.GetString("LABEL_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Edit ähnelt.
        /// </summary>
        public static string MENUITEM_EDIT {
            get {
                return ResourceManager.GetString("MENUITEM_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _File ähnelt.
        /// </summary>
        public static string MENUITEM_FILE {
            get {
                return ResourceManager.GetString("MENUITEM_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Help ähnelt.
        /// </summary>
        public static string MENUITEM_HELP {
            get {
                return ResourceManager.GetString("MENUITEM_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monthly balance: {0} ähnelt.
        /// </summary>
        public static string MONTH_BALANCE_0 {
            get {
                return ResourceManager.GetString("MONTH_BALANCE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to create the sheet for {0}? ähnelt.
        /// </summary>
        public static string QUESTION_CREATE_SHEET_0 {
            get {
                return ResourceManager.GetString("QUESTION_CREATE_SHEET_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to delete the account &apos;{0}&apos;? ähnelt.
        /// </summary>
        public static string QUESTION_DELETE_ACCOUNT_0 {
            get {
                return ResourceManager.GetString("QUESTION_DELETE_ACCOUNT_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to delete the selected bookings? ähnelt.
        /// </summary>
        public static string QUESTION_DELETE_ITEMS {
            get {
                return ResourceManager.GetString("QUESTION_DELETE_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to delete the sheet for {0}? ähnelt.
        /// </summary>
        public static string QUESTION_DELETE_SHEET_0 {
            get {
                return ResourceManager.GetString("QUESTION_DELETE_SHEET_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} of {1} booking selected. ähnelt.
        /// </summary>
        public static string SELECTED_0_OF_1 {
            get {
                return ResourceManager.GetString("SELECTED_0_OF_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1 booking selected. ähnelt.
        /// </summary>
        public static string SELECTED_ONE {
            get {
                return ResourceManager.GetString("SELECTED_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total: {0}. Average per booking: {1}. ähnelt.
        /// </summary>
        public static string STATUS_AMOUNT_0_1 {
            get {
                return ResourceManager.GetString("STATUS_AMOUNT_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Average balance per month: {0}. ähnelt.
        /// </summary>
        public static string STATUS_AVERAGE_PER_MONTH_0 {
            get {
                return ResourceManager.GetString("STATUS_AVERAGE_PER_MONTH_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copyright 2017 Niels Stockfleth
        ///
        ///This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
        ///
        ///This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details. ähnelt.
        /// </summary>
        public static string TEXT_COPYRIGHT {
            get {
                return ResourceManager.GetString("TEXT_COPYRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the balance for the first of {0}. ähnelt.
        /// </summary>
        public static string TEXT_ENTER_ACCOUNT_BALANCE_0 {
            get {
                return ResourceManager.GetString("TEXT_ENTER_ACCOUNT_BALANCE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose the import directory with the account data in the old format. ähnelt.
        /// </summary>
        public static string TEXT_SELECT_IMPORT_DIRECTORY {
            get {
                return ResourceManager.GetString("TEXT_SELECT_IMPORT_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add booking ähnelt.
        /// </summary>
        public static string TITLE_ADD {
            get {
                return ResourceManager.GetString("TITLE_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add regular booking ähnelt.
        /// </summary>
        public static string TITLE_ADD_DEFAULT_BOOKING {
            get {
                return ResourceManager.GetString("TITLE_ADD_DEFAULT_BOOKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bank Account Manager ähnelt.
        /// </summary>
        public static string TITLE_BANK {
            get {
                return ResourceManager.GetString("TITLE_BANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configure regular bookings ähnelt.
        /// </summary>
        public static string TITLE_CONFIGURE_DEFAULT_BOOKING {
            get {
                return ResourceManager.GetString("TITLE_CONFIGURE_DEFAULT_BOOKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configure default texts ähnelt.
        /// </summary>
        public static string TITLE_CONFIGURE_DEFAULT_TEXT {
            get {
                return ResourceManager.GetString("TITLE_CONFIGURE_DEFAULT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit booking ähnelt.
        /// </summary>
        public static string TITLE_EDIT {
            get {
                return ResourceManager.GetString("TITLE_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit regular booking ähnelt.
        /// </summary>
        public static string TITLE_EDIT_DEFAULT_BOOKING {
            get {
                return ResourceManager.GetString("TITLE_EDIT_DEFAULT_BOOKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit default text ähnelt.
        /// </summary>
        public static string TITLE_EDIT_DEFAULT_TEXT {
            get {
                return ResourceManager.GetString("TITLE_EDIT_DEFAULT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verify password ähnelt.
        /// </summary>
        public static string TITLE_ENTER_PASSWORD {
            get {
                return ResourceManager.GetString("TITLE_ENTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new account ähnelt.
        /// </summary>
        public static string TITLE_NEW {
            get {
                return ResourceManager.GetString("TITLE_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename account ähnelt.
        /// </summary>
        public static string TITLE_RENAME_ACCOUNT {
            get {
                return ResourceManager.GetString("TITLE_RENAME_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set password ähnelt.
        /// </summary>
        public static string TITLE_SET_PASSWORD {
            get {
                return ResourceManager.GetString("TITLE_SET_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update sheet ähnelt.
        /// </summary>
        public static string TITLE_UPDATE_BALANCE {
            get {
                return ResourceManager.GetString("TITLE_UPDATE_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add booking ähnelt.
        /// </summary>
        public static string TOOLTIP_ADD {
            get {
                return ResourceManager.GetString("TOOLTIP_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete booking ähnelt.
        /// </summary>
        public static string TOOLTIP_DELETE {
            get {
                return ResourceManager.GetString("TOOLTIP_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit booking ähnelt.
        /// </summary>
        public static string TOOLTIP_EDIT {
            get {
                return ResourceManager.GetString("TOOLTIP_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First month ähnelt.
        /// </summary>
        public static string TOOLTIP_FIRST {
            get {
                return ResourceManager.GetString("TOOLTIP_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last month ähnelt.
        /// </summary>
        public static string TOOLTIP_LAST {
            get {
                return ResourceManager.GetString("TOOLTIP_LAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next month ähnelt.
        /// </summary>
        public static string TOOLTIP_NEXT {
            get {
                return ResourceManager.GetString("TOOLTIP_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Previous month ähnelt.
        /// </summary>
        public static string TOOLTIP_PREVIOUS {
            get {
                return ResourceManager.GetString("TOOLTIP_PREVIOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} bookings. ähnelt.
        /// </summary>
        public static string TOTAL_0 {
            get {
                return ResourceManager.GetString("TOTAL_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1 booking. ähnelt.
        /// </summary>
        public static string TOTAL_ONE {
            get {
                return ResourceManager.GetString("TOTAL_ONE", resourceCulture);
            }
        }
    }
}
